#pragma once

#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP4
#define POINTING_DEVICE_CS_PIN GP5

#define CIRQUE_PINNACLE_DIAMETER_MM 40
#define POINTING_DEVICE_ROTATION_270
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_CIRCULAR_SCROLL_ENABLE

#define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_INVERT_X
