#pragma once

// Define options
#define TAPPING_TERM 135
#define PERMISSIVE_HOLD
#define TAPPING_TERM_PER_KEY
#define RGB_BRIGHTNESS 8
#define COMBO_TERM 20
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_SHOULD_TRIGGER

// Mouse keys
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_TIME_TO_MAX 40
